#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# create_dvp.tcl: Tcl script for re-creating project 'dvp'
#
# Generated by Vivado on Thu Jan 19 02:34:16 +0900 2023
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_dvp.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/fifo_frm/fifo_frm.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_obuf_fifo/gftt_obuf_fifo.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_sqrt/gftt_sqrt.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_box_ram/gftt_box_ram.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_ibuf_ram/gftt_ibuf_ram.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/bm_obuf2_fifo/bm_obuf2_fifo.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/bm_obuf_fifo/bm_obuf_fifo.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/tdpram_340_1024/tdpram_340_1024.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/bm_calc_dly/bm_calc_dly.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/dpram_64_1024/dpram_64_1024.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/dpram_32_512/dpram_32_512.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/dpram_36_512/dpram_36_512.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/rect_obuf_dff/rect_obuf_dff.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/rect_dly2/rect_dly2.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/cmd_cue/cmd_cue.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/rect_line_buf/rect_line_buf.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/grb_fifo/grb_fifo.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/csi_dly_fifo/csi_dly_fifo.xci"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/arb.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/axi_if.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_det.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_frac.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_sad.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_uni.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_upd.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_ibuf.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_ibuf_lr.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_ibuf_sad.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_obuf.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_obuf2.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/clkx.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/clkx2.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/csi_dly.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/csi_if.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/csi_if_ch.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/diven.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/frame_meas.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_box.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_eig.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_ibuf.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_obuf.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_sbl.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/grb.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_ibuf.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_intp.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_intp_fifo.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_obuf.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_rmp.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/simple_fifo.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/xsbl2.v"
#    "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/dvp.v"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/fifo_frm/fifo_frm.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_obuf_fifo/gftt_obuf_fifo.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_sqrt/gftt_sqrt.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_box_ram/gftt_box_ram.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/gftt_ibuf_ram/gftt_ibuf_ram.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/bm_obuf2_fifo/bm_obuf2_fifo.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/bm_obuf_fifo/bm_obuf_fifo.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/tdpram_340_1024/tdpram_340_1024.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/bm_calc_dly/bm_calc_dly.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/dpram_64_1024/dpram_64_1024.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/dpram_32_512/dpram_32_512.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/dpram_36_512/dpram_36_512.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/rect_obuf_dff/rect_obuf_dff.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/rect_dly2/rect_dly2.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/cmd_cue/cmd_cue.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/rect_line_buf/rect_line_buf.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/grb_fifo/grb_fifo.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/ip/csi_dly_fifo/csi_dly_fifo.xci" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/arb.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/axi_if.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_det.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_frac.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_sad.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_uni.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_calc_upd.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_ibuf.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_ibuf_lr.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_ibuf_sad.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_obuf.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/bm_obuf2.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/clkx.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/clkx2.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/csi_dly.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/csi_if.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/csi_if_ch.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/diven.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/frame_meas.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_box.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_eig.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_ibuf.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_obuf.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/gftt_sbl.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/grb.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_ibuf.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_intp.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_intp_fifo.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_obuf.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/rect_rmp.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/simple_fifo.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/xsbl2.v" \
   "C:/Users/luber/Documents/work/projects/U96-SLAM/src/dvp/rtl/dvp.v" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "dvp"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "create_dvp.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/dvp"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xczu3eg-sbva484-1-i

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../../../../AppData/Roaming/Xilinx/Vivado/2020.2/xhub/board_store/xilinx_board_store"]" -objects $obj
set_property -name "board_part" -value "avnet.com:ultra96v2:part0:1.2" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "ultra96v2" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "92" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "92" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "92" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "92" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "92" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "92" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "92" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "92" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../src/dvp/ip/fifo_frm/fifo_frm.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/gftt_obuf_fifo/gftt_obuf_fifo.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/gftt_sqrt/gftt_sqrt.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/gftt_box_ram/gftt_box_ram.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/gftt_ibuf_ram/gftt_ibuf_ram.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/bm_obuf2_fifo/bm_obuf2_fifo.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/bm_obuf_fifo/bm_obuf_fifo.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/tdpram_340_1024/tdpram_340_1024.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/bm_calc_dly/bm_calc_dly.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/dpram_64_1024/dpram_64_1024.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/dpram_32_512/dpram_32_512.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/dpram_36_512/dpram_36_512.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/rect_obuf_dff/rect_obuf_dff.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/rect_dly2/rect_dly2.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/cmd_cue/cmd_cue.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/rect_line_buf/rect_line_buf.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/grb_fifo/grb_fifo.xci"] \
 [file normalize "${origin_dir}/../src/dvp/ip/csi_dly_fifo/csi_dly_fifo.xci"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/arb.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/axi_if.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_calc.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_calc_det.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_calc_frac.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_calc_sad.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_calc_uni.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_calc_upd.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_ibuf.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_ibuf_lr.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_ibuf_sad.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_obuf.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/bm_obuf2.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/clkx.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/clkx2.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/csi_dly.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/csi_if.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/csi_if_ch.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/diven.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/frame_meas.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/gftt.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/gftt_box.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/gftt_eig.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/gftt_ibuf.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/gftt_obuf.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/gftt_sbl.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/grb.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/rect.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/rect_ibuf.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/rect_intp.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/rect_intp_fifo.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/rect_obuf.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/rect_rmp.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/simple_fifo.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/xsbl2.v"] \
 [file normalize "${origin_dir}/../src/dvp/rtl/dvp.v"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../src/dvp/ip/fifo_frm/fifo_frm.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/gftt_obuf_fifo/gftt_obuf_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/gftt_sqrt/gftt_sqrt.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/gftt_box_ram/gftt_box_ram.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/gftt_ibuf_ram/gftt_ibuf_ram.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/bm_obuf2_fifo/bm_obuf2_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/bm_obuf_fifo/bm_obuf_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/tdpram_340_1024/tdpram_340_1024.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/bm_calc_dly/bm_calc_dly.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/dpram_64_1024/dpram_64_1024.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/dpram_32_512/dpram_32_512.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/dpram_36_512/dpram_36_512.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/rect_obuf_dff/rect_obuf_dff.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/rect_dly2/rect_dly2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/cmd_cue/cmd_cue.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/rect_line_buf/rect_line_buf.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/grb_fifo/grb_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../src/dvp/ip/csi_dly_fifo/csi_dly_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "dvp" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "dvp" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xczu3eg-sbva484-1-i -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xczu3eg-sbva484-1-i -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
